### ISSUE TITLE
Problem when running on serverless 

### ISSUE THREAD

**Issue by danielvaughan** [rrahul963/serverless-export-swagger#2]
Hi, thanks for providing this.

Unfortunately, I experience an error on deployment when attempting to use the extension on 
```
     OS:                     linux
     Node Version:           6.14.2
     Serverless Version:     1.29.0
```
even when I use similar config to the README:

```
plugins:
  - serverless-export-swagger

custom:
  swaggerDestinations:
    s3BucketName: 'indy-ingest-swagger-1'
        s3KeyName: 'swagger/api.json'
    acl: public-read
```
I get the message:

```
Serverless plugin "serverless-export-swagger" initialization errored: Unexpected token )
```

**Comment by rrahul963** [comment]
can you try 
```
custom:
  swaggerDestinations:
    s3BucketName: 'indy-ingest-swagger-1'
    s3KeyName: 'swagger/api.json'
    acl: public-read
```
